baseURL: "https://cobusuys.com/"
title: Cobus Uys' Blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-PSNTC0MPCR

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Cobus Uys' Blog
  description: "I'm learning about marketing and business growth and I'm documenting the journey for everyone to follow along."
  keywords: [Blog, Business, Marketing, Advertising, Real-Estate, Property]
  author: Cobus Uys
  # author: ["Me", "You"] # multiple authors
  images: ["images/pfp_bg.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "images/favicon.ico"
    favicon16x16: "images/favicon-16x16.png"
    favicon32x32: "images/favicon-32x32.png"
    apple_touch_icon: "images/apple-touch-icon.png"
    safari_pinned_tab: "images/apple-touch-icon.png"

  label:
    text: "Cobus Uys' Blog"
    icon: images/apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Welcome to my blog!🤝
    subtitle: "I'm learning how to run a business and how to do effective marketing, so I thought I might as as well document the process."
    imageUrl: "images/pfp_bg.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: profile picture
    buttons:
      - name: Archive
        url: /archives/
      - name: Search
        url: /search/

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/cobus-uys/"
    - name: tiktok
      url: "https://www.tiktok.com/@cobusuys"
    - name: youtube
      url: "https://www.youtube.com/channel/UCC6fGWswEHPBjfnH_n0dnFQ"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 10
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary